// <auto-generated />
using System;
using IznajmljivanjeKonzola.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IznajmljivanjeKonzola.Infrastructure.Migrations
{
    [DbContext(typeof(IznajmljivanjeContext))]
    [Migration("20260624121303_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Iznajmljivanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlijentId")
                        .HasColumnType("int");

                    b.Property<int>("RadnikId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlijentId");

                    b.HasIndex("RadnikId");

                    b.ToTable("Iznajmljivanja", (string)null);
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Klijent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MestoId")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MestoId");

                    b.ToTable("Klijenti", (string)null);
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Mesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mesta", (string)null);
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Oprema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DatumNabavke")
                        .HasColumnType("datetime2");

                    b.Property<string>("InventarskiBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proizvodjac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stanje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipOpreme")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("InventarskiBroj")
                        .IsUnique();

                    b.ToTable("Oprema", (string)null);

                    b.HasDiscriminator<string>("TipOpreme").HasValue("Oprema");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Radnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.ToTable("Radnici", (string)null);
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Stavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojSati")
                        .HasColumnType("int");

                    b.Property<int>("IznajmljivanjeId")
                        .HasColumnType("int");

                    b.Property<int>("OpremaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IznajmljivanjeId");

                    b.HasIndex("OpremaId");

                    b.ToTable("Stavka", (string)null);
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.DodatnaOprema", b =>
                {
                    b.HasBaseType("IznajmljivanjeKonzola.Domain.Oprema");

                    b.Property<bool>("Bezicna")
                        .HasColumnType("bit");

                    b.Property<int?>("KapacitetBaterijeMah")
                        .HasColumnType("int");

                    b.Property<string>("KompatibilanModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipDodatneOpreme");

                    b.HasDiscriminator().HasValue("DodatnaOprema");
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Konzola", b =>
                {
                    b.HasBaseType("IznajmljivanjeKonzola.Domain.Oprema");

                    b.Property<int>("BrojKontrolera")
                        .HasColumnType("int");

                    b.Property<int>("KapacitetSkladistaGb")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PodrzavaVr")
                        .HasColumnType("bit");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipKonzole");

                    b.HasDiscriminator().HasValue("Konzola");
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Iznajmljivanje", b =>
                {
                    b.HasOne("IznajmljivanjeKonzola.Domain.Klijent", "Klijent")
                        .WithMany("Iznajmljivanja")
                        .HasForeignKey("KlijentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Iznajmljivanje_Klijent");

                    b.HasOne("IznajmljivanjeKonzola.Domain.Radnik", "Radnik")
                        .WithMany("Iznajmljivanja")
                        .HasForeignKey("RadnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Iznajmljivanje_Radnik");

                    b.Navigation("Klijent");

                    b.Navigation("Radnik");
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Klijent", b =>
                {
                    b.HasOne("IznajmljivanjeKonzola.Domain.Mesto", "Mesto")
                        .WithMany("Klijenti")
                        .HasForeignKey("MestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Klijent_Mesto");

                    b.Navigation("Mesto");
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Stavka", b =>
                {
                    b.HasOne("IznajmljivanjeKonzola.Domain.Iznajmljivanje", "Iznajmljivanje")
                        .WithMany("Stavke")
                        .HasForeignKey("IznajmljivanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Stavka_Iznajmljivanje");

                    b.HasOne("IznajmljivanjeKonzola.Domain.Oprema", "Oprema")
                        .WithMany("Stavke")
                        .HasForeignKey("OpremaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Stavka_Oprema");

                    b.Navigation("Iznajmljivanje");

                    b.Navigation("Oprema");
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Iznajmljivanje", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Klijent", b =>
                {
                    b.Navigation("Iznajmljivanja");
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Mesto", b =>
                {
                    b.Navigation("Klijenti");
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Oprema", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("IznajmljivanjeKonzola.Domain.Radnik", b =>
                {
                    b.Navigation("Iznajmljivanja");
                });
#pragma warning restore 612, 618
        }
    }
}
